### ISSUE TITLE
"No key could be detected" error

### ISSUE THREAD

**Issue by mattstratton** [robinske/wthik#1]
First of all, yay for an awesome tool :)

I've attempted to shove everything into heroku config vars, but when I hit the endpoint from Twilio, I get the error:
```
2018-06-12T21:12:11.748893+00:00 app[web.1]: [2018-06-12 21:12:11,745] ERROR in app: Exception on /sms [POST]
2018-06-12T21:12:11.748920+00:00 app[web.1]: Traceback (most recent call last):
2018-06-12T21:12:11.748923+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
2018-06-12T21:12:11.748925+00:00 app[web.1]: response = self.full_dispatch_request()
2018-06-12T21:12:11.748928+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
2018-06-12T21:12:11.748930+00:00 app[web.1]: rv = self.handle_user_exception(e)
2018-06-12T21:12:11.748931+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
2018-06-12T21:12:11.748933+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2018-06-12T21:12:11.748935+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
2018-06-12T21:12:11.748938+00:00 app[web.1]: raise value
2018-06-12T21:12:11.748940+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
2018-06-12T21:12:11.748942+00:00 app[web.1]: rv = self.dispatch_request()
2018-06-12T21:12:11.748944+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
2018-06-12T21:12:11.748946+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2018-06-12T21:12:11.748948+00:00 app[web.1]: File "/app/wthik.py", line 145, in main
2018-06-12T21:12:11.748950+00:00 app[web.1]: credentials = _get_credentials()
2018-06-12T21:12:11.748952+00:00 app[web.1]: File "/app/wthik.py", line 27, in _get_credentials
2018-06-12T21:12:11.748954+00:00 app[web.1]: subject=app.config.get("SUBJECT"))
2018-06-12T21:12:11.748957+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/google/oauth2/service_account.py", line 193, in from_service_account_info
2018-06-12T21:12:11.748958+00:00 app[web.1]: info, require=['client_email', 'token_uri'])
2018-06-12T21:12:11.748961+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/google/auth/_service_account_info.py", line 54, in from_dict
2018-06-12T21:12:11.748963+00:00 app[web.1]: signer = crypt.RSASigner.from_service_account_info(data)
2018-06-12T21:12:11.748965+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/google/auth/crypt/base.py", line 115, in from_service_account_info
2018-06-12T21:12:11.748967+00:00 app[web.1]: info.get(_JSON_FILE_PRIVATE_KEY_ID))
2018-06-12T21:12:11.748968+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/google/auth/crypt/_python_rsa.py", line 174, in from_string
2018-06-12T21:12:11.748981+00:00 app[web.1]: ValueError: No key could be detected.
2018-06-12T21:12:11.748970+00:00 app[web.1]: raise ValueError('No key could be detected.')
```

I've attached a screenshot of my config vars (with data redacted)

![image](https://user-images.githubusercontent.com/1280666/41317848-42bd0dd6-6e4b-11e8-9bea-538eac52f0f9.png)

I've tried putting the private key in quotes and not in quotes, and it doesn't seem to matter.

**Comment by robinske** [comment]
What does your `app_config.py` look like? The fix might be to add the following to `app_config.py` if you don't already have it:

```SUBJECT = os.environ["CALENDAR_SUBJECT"]```

**Comment by mattstratton** [comment]
It's identical to yours, except I changed my name :)

https://github.com/mattstratton/wthik/blob/master/app_config.py

**Comment by robinske** [comment]
ooo I think I remember the problem here - it might have to do with the formatting of your Private Key. I can't recall exactly what I did to set it, but it needs to include the newlines (but no `\n` chars) and such. Here's the shape of mine from `heroku config`:

![image](https://user-images.githubusercontent.com/3673341/41318418-1cc5e380-6e4d-11e8-9667-66632581ee29.png)

**Comment by mattstratton** [comment]
That got past that error...I discovered that the Heroku text box will expand if you paste in something with carriage returns.

Now I get this fun part:

```
2018-06-12T21:40:11.474261+00:00 app[web.1]: [2018-06-12 21:40:11,470] ERROR in app: Exception on /sms [POST]
2018-06-12T21:40:11.474286+00:00 app[web.1]: Traceback (most recent call last):
2018-06-12T21:40:11.474288+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
2018-06-12T21:40:11.474290+00:00 app[web.1]: response = self.full_dispatch_request()
2018-06-12T21:40:11.474292+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
2018-06-12T21:40:11.474293+00:00 app[web.1]: rv = self.handle_user_exception(e)
2018-06-12T21:40:11.474295+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
2018-06-12T21:40:11.474296+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2018-06-12T21:40:11.474299+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
2018-06-12T21:40:11.474301+00:00 app[web.1]: raise value
2018-06-12T21:40:11.474302+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
2018-06-12T21:40:11.474304+00:00 app[web.1]: rv = self.dispatch_request()
2018-06-12T21:40:11.474306+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
2018-06-12T21:40:11.474308+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2018-06-12T21:40:11.474309+00:00 app[web.1]: File "/app/wthik.py", line 156, in main
2018-06-12T21:40:11.474311+00:00 app[web.1]: return travel_schedule(service, calendar_id)
2018-06-12T21:40:11.474312+00:00 app[web.1]: File "/app/wthik.py", line 116, in travel_schedule
2018-06-12T21:40:11.474314+00:00 app[web.1]: orderBy='startTime'
2018-06-12T21:40:11.474316+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
2018-06-12T21:40:11.474318+00:00 app[web.1]: return wrapped(*args, **kwargs)
2018-06-12T21:40:11.474320+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/googleapiclient/http.py", line 835, in execute
2018-06-12T21:40:11.474322+00:00 app[web.1]: method=str(self.method), body=self.body, headers=self.headers)
2018-06-12T21:40:11.474323+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/googleapiclient/http.py", line 162, in _retry_request
2018-06-12T21:40:11.474325+00:00 app[web.1]: resp, content = http.request(uri, method, *args, **kwargs)
2018-06-12T21:40:11.474326+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/google_auth_httplib2.py", line 187, in request
2018-06-12T21:40:11.474328+00:00 app[web.1]: self._request, method, uri, request_headers)
2018-06-12T21:40:11.474330+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/google/auth/credentials.py", line 122, in before_request
2018-06-12T21:40:11.474332+00:00 app[web.1]: self.refresh(request)
2018-06-12T21:40:11.474333+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/google/oauth2/service_account.py", line 322, in refresh
2018-06-12T21:40:11.474335+00:00 app[web.1]: request, self._token_uri, assertion)
2018-06-12T21:40:11.474337+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
2018-06-12T21:40:11.474339+00:00 app[web.1]: response_data = _token_endpoint_request(request, token_uri, body)
2018-06-12T21:40:11.474340+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/google/oauth2/_client.py", line 111, in _token_endpoint_request
2018-06-12T21:40:11.474342+00:00 app[web.1]: _handle_error_response(response_body)
2018-06-12T21:40:11.474344+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/google/oauth2/_client.py", line 61, in _handle_error_response
2018-06-12T21:40:11.474346+00:00 app[web.1]: error_details, response_body)
2018-06-12T21:40:11.474355+00:00 app[web.1]: google.auth.exceptions.RefreshError: ('unauthorized_client: Client is unauthorized to retrieve access tokens using this method.', '{\n  "error" : "unauthorized_client",\n  "error_description" : "Client is unauthorized to retrieve access tokens using this method."\n}')
```

(Thank you for your patience - I mostly am hoping that this will help someone else if they bump their head too!)

**Comment by mattstratton** [comment]
I think I figured it out.

This won't work on a Gmail account as the subject, from what I can determine from https://stackoverflow.com/questions/42784640/client-is-unauthorized-to-retrieve-access-tokens-using-this-method-gmail-api-c-s

Since I use my Gmail calendar for All the Things, this likely won't work out. Probably not a bad disclaimer for the README/blog, unless I'm incorrect?

**Comment by robinske** [comment]
Ahh. That might be true for that implementation - try it with these changes: https://github.com/robinske/wthik/compare/use-oauth2client?expand=1

You have to share your calendar with the `client_email` but this might work with *.gmail accounts - I'll test both ways with my `gmail.com` account now.

**Comment by mattstratton** [comment]
Aha! I merged those changes into my fork, and now it works like a delight!

**Comment by robinske** [comment]
Hooray! I'll push those changes to master.

**Comment by lukenamop** [comment]
Thank you for this thread! I was also using Heroku and having this error, I solved it by replacing `\n` with actual newlines.

**Comment by mohamedhafezqo** [comment]
`"private_key": os.environ.get('PRIVATE_KEY').replace('\\n', '\n'),
`

**Comment by nimit2801** [comment]
> 
> 
> ooo I think I remember the problem here - it might have to do with the formatting of your Private Key. I can't recall exactly what I did to set it, but it needs to include the newlines (but no `\n` chars) and such. Here's the shape of mine from `heroku config`:
> 
> ![image](https://user-images.githubusercontent.com/3673341/41318418-1cc5e380-6e4d-11e8-9667-66632581ee29.png)

Thanks for this solution it works fine for me ✅

**Comment by NathanHam16** [comment]
> > ooo I think I remember the problem here - it might have to do with the formatting of your Private Key. I can't recall exactly what I did to set it, but it needs to include the newlines (but no `\n` chars) and such. Here's the shape of mine from `heroku config`:
> > ![image](https://user-images.githubusercontent.com/3673341/41318418-1cc5e380-6e4d-11e8-9667-66632581ee29.png)
> 
> Thanks for this solution it works fine for me ✅

What code do you have when parsing the variable into your program? None of these solutions work for me :(((((
